### ISSUE TITLE
Click interaction is weird/not obvious

### ISSUE THREAD

**Issue by omgmog** [yeskunall/lazy-colors#2]
Hello -- first of all, this is a lovely project, so thanks!

I wonder if it's worth adding an instruction that explains that clicking the page changes the color and clicking the "button" copies the current color the clipboard.

Also, it might be worth disabling the color change when clicking the button, as it's weird to copy one color and then display another.

Cheers!

**Comment by yeskunall** [comment]
Hit there! :grin: glad to hear you like the idea behind my project.

You're totally right. A little bit more explanation as to what this tool does will be helpful. I was going to do that in the near future, but seeing as you have already mentioned it, I will get on adding that feature to the site *immediately*.

As for your second suggestion: if you've dived a bit into my code, you will notice that currently the `click` event is registered to the entire `body` tag. I did that so that the user could click anywhere on the window and change the color. Now the problem with adding a click event to the entire body is what is causing the color to change even when the user only copies the text. I'm not a master at this, but I think I can still fix this. Any input or *more* suggestions are more than welcome.
